// Top-level build file where you can add configuration options common to all sub-projects/modules.

plugins {
    id "com.android.application" version "8.9.0" apply false
    id "org.jetbrains.kotlin.android" version "1.9.23" apply false
}


allprojects {
    repositories {


        google()
        mavenCentral()
        maven { url "https://www.jitpack.io" }
        //jcenter 阿里云镜像
        maven { url "https://maven.aliyun.com/repository/public" }

        maven { url 'https://maven.aliyun.com/nexus/content/repositories/google' }

        maven { url "https://maven.aliyun.com/repository/apache-snapshots" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    CLIP_PATH_LAYOUT_VERSION = '2.0.0'
    compileSdkVersion = 34
    minSdkVersion = 21
    targetSdkVersion = 34
}